title: Open NEC
description: A free and open-source Train Simulator Classic mod for Northeast Corridor locomotives.
theme: just-the-docs

url: https://opennec.trinancrat.me

favicon_ico: /assets/favicon.png

nav_external_links:
  - title: Download
    url: https://github.com/YoRyan/open-nec/releases
  - title: Issues
    url: https://github.com/YoRyan/open-nec/issues
  - title: Roadmap
    url: https://github.com/users/YoRyan/projects/6
  - title: Source
    url: https://github.com/YoRyan/open-nec

aux_links:
  Edit on GitHub: https://github.com/YoRyan/open-nec-website
